name: vendure
description: A Dart SDK for Vendure Open Source headless commerce framework.
version: 0.1.0
homepage: https://github.com/arrrrny/vendure-dart-sdk

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  graphql: ^5.0.0
  http: ^0.13.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.12